### ISSUE TITLE
bulk RNA seq (unzip)

### ISSUE THREAD

**Issue by livnatje** [Jerby-Lab/opipes#1]
@christineyyeh, any reason you are unzipping the fastq files?

**Comment by christineyyeh** [comment]
@livnatje oh; I had only realized after I had done the processing that you didn't need to unzip for the process to run so the unzipping step is a hold over. if you don't unzip, i believe it will still work. if you do try it without unzipping, let me know what happens!

**Comment by livnatje** [comment]
Yes, fastq->counts is usually okay with zipped files, but I'll let you know. I'll write a generic bash and upload for everyone to use. 
tnx
